#App customization
#Fri Sep 18 00:43:01 CEST 2026
autoResizeTimerFont=true
bandBackgroundMode=COLOR
bandCount=4
bandHeight=50
defaultProjectFormat=rythmo
globalBandImagePath=
historyBackground=-15198184
historyImagePath=
mediaBackground=-14803426
mediaImagePath=
perBandImagePaths=
showWaveform=true
timelineCursor=-2346446
timelineCursorX=80
timelineEvenBand=-14342874
timelineFontFamily=Segoe UI
timelineGrid=-11513776
timelineOddBand=-13816528
timelineSelectedBand=-13487546
timelineSeparator=-16725761
timerBackground=-15198184
timerFontSize=36
timerImagePath=
timerPanelWidth=180
timerTextColor=-1644826
waveformColor=671134975
