#Keybinds
#Mon Sep 14 19:14:10 CEST 2026
avanceMSCode=39
finPhraseCode=99
marcheArretCode=32
reculerMSCode=37
retourDebutCode=40
separateurKeyCode=100
signeFvrCode=101
signeMpbCode=100
signeNeutralCode=102
signeRespirationCode=104
signeVoyelleCode=103
zoomInCode=107
zoomOutCode=109
